-- coop_nextjs schema for Supabase (PostgreSQL)
-- Run in Supabase SQL Editor (public schema)

CREATE TABLE IF NOT EXISTS public.daily_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id VARCHAR(20) NOT NULL,
  report_date DATE NOT NULL,
  work_start_time TIME NULL,
  work_end_time TIME NULL,
  department VARCHAR(255) NULL,
  work_summary TEXT NULL,
  problem TEXT NULL,
  fix_action TEXT NULL,
  experience TEXT NULL,
  suggestion TEXT NULL,
  student_signature_name VARCHAR(255) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_daily_reports_student_date UNIQUE (student_id, report_date)
);

CREATE INDEX IF NOT EXISTS idx_daily_reports_student_id
  ON public.daily_reports (student_id);
CREATE INDEX IF NOT EXISTS idx_daily_reports_report_date
  ON public.daily_reports (report_date);

CREATE TABLE IF NOT EXISTS public.weekly_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id VARCHAR(20) NOT NULL,
  semester_year INT NOT NULL,
  semester_no SMALLINT NOT NULL CHECK (semester_no BETWEEN 1 AND 3),
  week_no SMALLINT NOT NULL CHECK (week_no BETWEEN 1 AND 40),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  department VARCHAR(255) NULL,
  work_summary TEXT NULL,
  problem TEXT NULL,
  status TEXT NOT NULL DEFAULT 'normal'
    CHECK (status IN ('good', 'normal', 'worse', 'danger')),
  fix_action TEXT NULL,
  course_fix_action TEXT NULL,
  experience TEXT NULL,
  suggestion TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_weekly_reports_student_semester_week UNIQUE (
    student_id, semester_year, semester_no, week_no
  )
);

CREATE INDEX IF NOT EXISTS idx_weekly_reports_student_id
  ON public.weekly_reports (student_id);
CREATE INDEX IF NOT EXISTS idx_weekly_reports_student_semester
  ON public.weekly_reports (student_id, semester_year, semester_no);
CREATE INDEX IF NOT EXISTS idx_weekly_reports_status
  ON public.weekly_reports (status);
CREATE INDEX IF NOT EXISTS idx_weekly_reports_dates
  ON public.weekly_reports (start_date, end_date);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_daily_reports_updated_at ON public.daily_reports;
CREATE TRIGGER trg_daily_reports_updated_at
BEFORE UPDATE ON public.daily_reports
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_weekly_reports_updated_at ON public.weekly_reports;
CREATE TRIGGER trg_weekly_reports_updated_at
BEFORE UPDATE ON public.weekly_reports
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE VIEW public.v_weekly_reports_export AS
SELECT
  id,
  student_id,
  semester_year,
  semester_no,
  week_no,
  start_date,
  end_date,
  COALESCE(department, '') AS department,
  COALESCE(work_summary, '') AS work_summary,
  COALESCE(problem, '') AS problem,
  status,
  COALESCE(fix_action, '') AS fix_action,
  COALESCE(course_fix_action, '') AS course_fix_action,
  COALESCE(experience, '') AS experience,
  COALESCE(suggestion, '') AS suggestion,
  created_at,
  updated_at
FROM public.weekly_reports;
